---
kind: pipeline
name: build and push pipeline
steps:
  - image: plugins/docker
    name: build + test + push
    settings:
      dry_run: false
      password:
        from_secret: docker-hub-password
      repo: grafana/plugin-validator-cli
      tags: latest
      username:
        from_secret: docker-hub-username
trigger:
  branch:
    include:
      - main
  event:
    include:
      - push
  paths:
    include:
      - go.mod
      - go.sum
      - "**/*.go"
type: docker
---
kind: pipeline
name: linters
steps:
  - commands:
      - apk add --no-cache make jsonnet
      - make lint-jsonnet
    image: alpine:3.17.0
    name: lint jsonnet
trigger:
  event:
    include:
      - pull_request
type: docker
---
get:
  name: username
  path: secret/data/common/docker-hub
kind: secret
name: docker-hub-username
---
get:
  name: password
  path: secret/data/common/docker-hub
kind: secret
name: docker-hub-password
---
kind: signature
hmac: 5c78a7c1196c1ef559d1699bd5126a01d76e56a3940a727e61085d9344ade9b3

...
