---
kind: pipeline
name: test docker build
steps:
  - image: plugins/docker
    name: build + test + push
    settings:
      dry_run: true
      password:
        from_secret: docker-hub-password
      repo: grafana/plugin-validator-cli
      tags: latest
      username:
        from_secret: docker-hub-username
trigger:
  branch:
    exclude:
      - main
  event:
    include:
      - push
      - pull_request
type: docker
---
kind: pipeline
name: build and push pipeline
steps:
  - image: plugins/docker
    name: build + test + push
    settings:
      dry_run: false
      password:
        from_secret: docker-hub-password
      repo: grafana/plugin-validator-cli
      tags: latest
      username:
        from_secret: docker-hub-username
trigger:
  branch:
    include:
      - main
  event:
    include:
      - push
type: docker
---
get:
  name: username
  path: secret/data/common/docker-hub
kind: secret
name: docker-hub-username
---
get:
  name: password
  path: secret/data/common/docker-hub
kind: secret
name: docker-hub-password
---
kind: signature
hmac: 931e3ddd7923cb1c3a3dfa888495ab6789a0ba731c9a018a7987fd8081ab286c

...
