---
kind: pipeline
name: build and push pipeline
steps:
  - image: plugins/docker
    name: build + test + push
    settings:
      dry_run: false
      password:
        from_secret: docker-hub-password
      repo: grafana/plugin-validator-cli
      tags: latest
      username:
        from_secret: docker-hub-username
trigger:
  branch:
    include:
      - main
  event:
    include:
      - push
type: docker
---
get:
  name: username
  path: secret/data/common/docker-hub
kind: secret
name: docker-hub-username
---
get:
  name: password
  path: secret/data/common/docker-hub
kind: secret
name: docker-hub-password
---
kind: signature
hmac: c53b967164396292dd774c23370f4ee7065f6afcc8d93a9bda01c46ba960106f

...
