name: Create release and publish to npm and docker hub

on:
  push:
    branches:
      - academo/remove-drone-pipeline

permissions:
  contents: read
  id-token: write

jobs:
  release-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version from package.json
        id: get_version
        run: |
          echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"

      - id: push-to-dockerhub
        uses: grafana/shared-workflows/actions/build-push-to-dockerhub@main
        with:
          repository: grafana/plugin-validator-cli
          context: .
          tags: |-
            "v${{ steps.get_version.outputs.version }}"
            "latest"
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
