name: Test Slack notification

on:
  push:
    branches:
      - fix-npm-stage-publishing

jobs:
  test-slack:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set fake tag name
        run: echo "TAG_NAME=plugin-validator/v0.42.9" >> "$GITHUB_ENV"

      - name: Notify Slack about staged npm package
        uses: grafana/shared-workflows/actions/send-slack-message@952ec381447a2002ff76103395d37bf8b4c7c3f5 # send-slack-message/v3.0.1
        with:
          method: chat.postMessage
          payload: |
            {
              "channel": "C031SLFH6G0",
              "text": "📦 TEST: This is a test notification for staged npm publishing workflow. Please ignore.`@grafana/plugin-validator` has been staged for npm publishing from tag `${{ env.TAG_NAME }}`. Please review and approve at https://www.npmjs.com/settings/grafanabot/staged-packages"
            }
